### ISSUE TITLE
Bundler could not find compatible versions for gem "activesupport":

### ISSUE THREAD

**Issue by wonderer007** [quandl/quandl-ruby#10]
I am using `quandl-ruby` gem with 

ruby version
`ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`

rails version
`Rails 4.2.1`

When I run `bundle install` I got following error

```
Bundler could not find compatible versions for gem "activesupport":
  In snapshot (Gemfile.lock):
    activesupport (= 4.2.1)

  In Gemfile:
    activeadmin was resolved to 1.0.0.pre4, which depends on
      arbre (>= 1.0.2, ~> 1.0) was resolved to 1.1.1, which depends on
        activesupport (>= 3.0.0)

    activeadmin was resolved to 1.0.0.pre4, which depends on
      inherited_resources (~> 1.6) was resolved to 1.7.0, which depends on
        has_scope (~> 0.6) was resolved to 0.7.0, which depends on
          activesupport (< 5.1, >= 4.1)

    jbuilder (~> 2.0) was resolved to 2.6.1, which depends on
      activesupport (< 5.1, >= 3.0.0)

    kaminari was resolved to 1.0.1, which depends on
      activesupport (>= 4.1.0)

    kaminari was resolved to 1.0.1, which depends on
      activesupport (>= 4.1.0)

    quandl was resolved to 1.0.3, which depends on
      activesupport (>= 4.2.3)

    rails (= 4.2.1) was resolved to 4.2.1, which depends on
      activesupport (= 4.2.1)

    rails (= 4.2.1) was resolved to 4.2.1, which depends on
      activesupport (= 4.2.1)

    rails (= 4.2.1) was resolved to 4.2.1, which depends on
      activesupport (= 4.2.1)

    rails (= 4.2.1) was resolved to 4.2.1, which depends on
      activesupport (= 4.2.1)

    rails (= 4.2.1) was resolved to 4.2.1, which depends on
      activesupport (= 4.2.1)

    rails (= 4.2.1) was resolved to 4.2.1, which depends on
      activesupport (= 4.2.1)

    rails (= 4.2.1) was resolved to 4.2.1, which depends on
      activesupport (= 4.2.1)

    activeadmin was resolved to 1.0.0.pre4, which depends on
      jquery-rails was resolved to 4.2.2, which depends on
        rails-dom-testing (< 3, >= 1) was resolved to 1.0.8, which depends on
          rails-deprecated_sanitizer (>= 1.0.1) was resolved to 1.0.3, which depends on
            activesupport (>= 4.2.0.alpha)

    activeadmin was resolved to 1.0.0.pre4, which depends on
      jquery-rails was resolved to 4.2.2, which depends on
        rails-dom-testing (< 3, >= 1) was resolved to 1.0.8, which depends on
          activesupport (< 5.0, >= 4.2.0.beta)

    activeadmin was resolved to 1.0.0.pre4, which depends on
      ransack (~> 1.3) was resolved to 1.8.2, which depends on
        activesupport (>= 3.0)

    rails (= 4.2.1) was resolved to 4.2.1, which depends on
      sprockets-rails was resolved to 3.2.0, which depends on
        activesupport (>= 4.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Then I figured out that **quandl** gem is using 

`'activesupport', '>= 4.2.3'`

while rails require my rails version require `activesupport` to be minimum at 4.2.1, I forked the repo and changed `'activesupport', '>= 4.2.3'` to `'activesupport', '>= 4.2.1'` and it works for me. If you get this error just add 

`gem 'quandl', github: 'wonderer007/quandl-ruby', branch: 'master'`

Also I am opening a PR for it.

Cheers

**Comment by wonderer007** [comment]
@michaelfich I had to change  active support  version in quandl.gemspec file to resolve this issue
from `spec.add_runtime_dependency 'activesupport', '>= 4.2.1'` to `spec.add_runtime_dependency 'activesupport', '>= 4.2.1'`

**Comment by michaelfich** [comment]
@wanderer007 My apologizes, I should have mentioned that I had taken a look at your PR.  The one concern I have is that downgrading a dependency to remove a patch version or two may not be wise.  However, if it becomes necessary, we'll definitely consider that.

**Comment by michaelfich** [comment]
@wonderer007 When you initially encountered the error, following a `bundle install`, did you try running `bundle update` as well?

**Comment by michaelfich** [comment]
@wonderer007,

The most recent versions of activesupport have provided valuable security updates and bugfixes.  I suggest that you upgrade your Rails app to version `4.2.8` to avoid any conflicts, rather than activesupport version downgrade for the `quandl-ruby` plugin.

An alternative is that you can also continue to use your forked version of this repo if you wish to proceed using Rails 4.2.1 instead.
