### ISSUE TITLE
ruby 2.4.1 json issue

### ISSUE THREAD

**Issue by topofocus** [quandl/quandl-ruby#12]
Hi,

the install-instructions (readme) are misleading ... 

somewhere a dependency to faraday is referenced ... and that requires explicitly json 1.7.7

after inserting "gem 'quande' to the gemfile and calling "bundle install" this happens

> Installing faraday 0.12.1

> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
> 
>     current directory: /home/topo/.rvm/gems/ruby-2.4.1/gems/json-1.7.7/ext/json/ext/generator
> /home/topo/.rvm/rubies/ruby-2.4.1/bin/ruby -r ./siteconf20170426-37298-1qr1mfx.rb extconf.rb
> creating Makefile
> 
> current directory: /home/topo/.rvm/gems/ruby-2.4.1/gems/json-1.7.7/ext/json/ext/generator
> make "DESTDIR=" clean
> 
> current directory: /home/topo/.rvm/gems/ruby-2.4.1/gems/json-1.7.7/ext/json/ext/generator
> make "DESTDIR="
> compiling generator.c
> In file included from generator.c:1:0:
> ../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
> ../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
>      VALUE result = rb_str_new(FBUFFER_PAIR(fb));
>                                                ^
> ../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [enabled by default]
>      VALUE result = rb_str_new(FBUFFER_PAIR(fb));
>                     ^
> generator.c: In function ‘generate_json’:
> generator.c:832:25: error: ‘rb_cFixnum’ undeclared (first use in this function)
>      } else if (klass == rb_cFixnum) {
>                          ^
> generator.c:832:25: note: each undeclared identifier is reported only once for each function it appears in
> generator.c:834:25: error: ‘rb_cBignum’ undeclared (first use in this function)
>      } else if (klass == rb_cBignum) {
>                          ^
> generator.c: At top level:
> cc1: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
> cc1: warning: unrecognized command line option "-Wno-constant-logical-operand" [enabled by default]
> cc1: warning: unrecognized command line option "-Wno-parentheses-equality" [enabled by default]
> cc1: warning: unrecognized command line option "-Wno-tautological-compare" [enabled by default]
> make: *** [generator.o] Fehler 1
> 
> make failed, exit code 2
> 
> Gem files will remain installed in /home/topo/.rvm/gems/ruby-2.4.1/gems/json-1.7.7 for inspection.
> Results logged to /home/topo/.rvm/gems/ruby-2.4.1/extensions/x86_64-linux/2.4.0/json-1.7.7/gem_make.out
> 
> An error occurred while installing json (1.7.7), and Bundler cannot continue.
> Make sure that `gem install json -v '1.7.7'` succeeds before bundling.
> 

Json 2.1.0 is installed

the gem is simply not usable.

This is disappointing  though its an official gem which should be »production ready«

**Comment by topofocus** [comment]
Second issue:

Changing the gemfile to

>  gem 'quandl' , :git => 'https://github.com/quandl/quandl-ruby'  # Quandl API

fires another error because you refer to an old version of REST-Client:

> topo@gamma:~/invest-orient$ bundle install
> Fetching https://github.com/quandl/quandl-ruby
> Fetching gem metadata from https://rubygems.org/...........
> Fetching version metadata from https://rubygems.org/..
> Fetching dependency metadata from https://rubygems.org/.
> Resolving dependencies...
> Bundler could not find compatible versions for gem "rest-client":
>   In snapshot (Gemfile.lock):
>     rest-client (= 2.0.1)
> 
>   In Gemfile:
>     active-orient was resolved to 0.6, which depends on
>       rest-client
> 
>     quandl was resolved to 1.0.3, which depends on
>       rest-client (~> 1.8.0)
> 

I suggest to update to the last stable release of the rest-client library to avoid this issue

**Comment by topofocus** [comment]
Something goes terribly wrong ...

following the instructions on the README,  i got

> data = Quandl::Dataset.get('WIKI/AAPL').data(params: { limit: 1 })
>  => {:meta=>{"limit"=>1, "transform"=>nil, "column_index"=>nil, "column_names"=>["1999-11-18", "45.5", "50.0", "40.0", "44.0", "44739900.0", "0.0", "1.0", "29.367758383040893", "32.272261959385595", "25.817809567508476", "28.399590524259324", "44739900.0"], "start_date"=>Fri, 12 Dec 1980, "end_date"=>Tue, 25 Apr 2017, "frequency"=>"daily", "collapse"=>nil, "order"=>nil}, :values=>[{"1999_11_18"=>Tue, 25 Apr 2017, "455"=>143.91, "500"=>144.9, "400"=>143.87, "440"=>144.54, "447399000"=>18216472.0, "00"=>0.0, "10"=>1.0, "29367758383040893"=>143.91, "32272261959385595"=>144.9, "25817809567508476"=>143.87, "28399590524259324"=>144.54}]} 
>

The column_names-field is not initialized. 

I am asking myself, if the gem is usable at all.

**Comment by laurenherdman** [comment]
Hello @topofocus,
We have updated the `quandl` gem to work with Ruby 2.4.1 [here](https://github.com/quandl/quandl-ruby/tree/1.0.4). If you continue to encounter issues please feel free to get in touch with us again.
