### ISSUE TITLE
Mismatch data points when data() function is called

### ISSUE THREAD

**Issue by Aiken00** [quandl/quandl-ruby#19]
The data can be fetched from Quandl sucessfully. However, when I try to get the data function I got the following error.

`Quandl::Dataset.get("JOHNMATT/PLAT").data( params: {limit:1})
`
Quandl::InvalidDataError: number of column names does not match number of data points in a row!

Is quandl changed its data format or something else?

EDITED: I checked the json api from quandl website here. It seems now the data source sometime skipped the field when there is no data available. (in this case the data fields NEW YORK data are skipped)

https://www.quandl.com/api/v3/datasets/JOHNMATT/PLAT.json?api_key=2MVpQPNBkBzLTGunfQPB&start_date=2017-10-01

**Comment by A-Scott-Rowe** [comment]
This does indeed look like an error in the data. We will investigate this issue and get back to you shortly.

**Comment by A-Scott-Rowe** [comment]
@Aiken00 

We’re aware of this issue with that particular database and currently working on fixing it. We don’t have an ETA just yet. In the mean time, the following code can be used and should work.

`Quandl::Dataset.get("JOHNMATT/PLAT").data(params: { limit: 1, column_index: [1,2,3,4] })`

I’ll close this issue for now but please let us know if you find any other issues.

**Comment by Aiken00** [comment]
Sorry but the point is that your gem does have a checking to see if the number of columns of headers is the same as your first line of dataset.
I will still get an error regardless of settings.

https://github.com/quandl/quandl-ruby/blob/b9c07916bf290d9042b1e27a45963933d6ef585b/lib/quandl/model/data.rb
