### ISSUE TITLE
RestClient::SSLCertificateNotVerified:        SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by taqtiqa-mark** [quandl/quandl-ruby#21]
I am getting the following error:

```bash
     RestClient::SSLCertificateNotVerified:
       SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
     Shared Example Group: "a generic source" called from ./spec/lib/quandl/fred_spec.rb:22
     # ./vendor/bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:758:in `rescue in transmit'
     # ./vendor/bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:642:in `transmit'
     # ./vendor/bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
     # ./vendor/bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
     # ./vendor/bundle/gems/quandl-1.1.0/lib/quandl/connection.rb:24:in `execute_request'
     # ./vendor/bundle/gems/quandl-1.1.0/lib/quandl/connection.rb:15:in `request'
     # ./vendor/bundle/gems/quandl-1.1.0/lib/quandl/operations/get.rb:9:in `get'
     # ./lib/macrodata/quandl/fred.rb:19:in `get_data'
 ```

The relevant part of the code does this:

```ruby
      def initialize(api_key=ENV['QUANDL_API_KEY'], api_version=ENV['QUANDL_API_VERSION'])
        ::Quandl::ApiConfig.api_key     = api_key
        ::Quandl::ApiConfig.api_version = api_version
        get_data
      end

      def get_data
        ::Quandl::Database.get('FRED').datasets do |ds_name|
          ds_data = ::Quandl::get("FRED/#{ds_name}").data
          create_table! ds_name
        end
      end
```

Appreciate any hints or tips.

**Comment by ericvautour-quandl** [comment]
Hello Mark,

I tested this call locally and it appears to work for me.  However, I have run into this issue in the past, and it was usually a configuration issue with my machine.  I was able to resolve it before by following hints provided here https://toadle.me/2015/04/16/fixing-failing-ssl-verification-with-rvm.html.

Thanks,

**Comment by taqtiqa-mark** [comment]
Quick notes (WIP):
The following will allow the `[doctor.rb](https://github.com/mislav/ssl-tools)` script to run
1. Identify the location your openssl installation is expecting to find certificates
```bash
$( openssl version -d | awk -F'"' '{print $2}' )
# /usr/local/ssl/
```
1. Confirm the `certs` subfolder at that location is empty:
```bash
ls -la $( openssl version -d | awk -F'"' '{print $2}' )/certs
```
1. Link your existing ssl certs folder to the one openssl expects
```bash
ln -s /etc/ssl/certs /usr/local/ssl/certs
```

TODO: 
a. Confirm this allows the Quandl script to complete
b. Documenation pull request

**Comment by mbasset** [comment]
Hi @taqtiqa-mark,

Were you able to resolve your issue? Is there anything you would suggest adding that is specific to our plugin that we can add to aid other users in the future?

**Comment by taqtiqa-mark** [comment]
Hi, thanks for looking at this.  I managed to get things working.  The only suggestion would be to add the steps I outlined. Either to the Readme.md or build them into the plugin with feedback.  Vagrants, recent, SSH feed back is a useful standard regarding feedback that guides people toward a remedy and away from an issue/ticket.

Happy for this to be closed, unless you want to track something.

**Comment by mbasset** [comment]
Thanks @taqtiqa-mark,

Since those steps are system dependent we will not be including them in our readme but this issue can hopefully provide guidance to those with similar setups. If this becomes a more widespread issue we might re-visit.
