### ISSUE TITLE
Bundler could not find compatible versions of bundler.

### ISSUE THREAD

**Issue by krupat17** [quandl/quandl-ruby#22]
![capture](https://user-images.githubusercontent.com/46721013/52130074-222ae400-2631-11e9-8897-72998e2d98cf.PNG)

I keep getting this error when I try to add the gem "Cancan". I have tried many solutions as suggested but nothing seems to be working.

**Comment by A-Scott-Rowe** [comment]
Can you provide more detail? Are you trying to add `cancan` to the quandl gem, Or use it in conjunction with quandl?

**Comment by A-Scott-Rowe** [comment]
I'm going to close this issue. feel free to open it back up if you continue to have problems.
