### ISSUE TITLE
bundler could not find compatiblee version for gem bundler in Gemfile 

### ISSUE THREAD

**Issue by umran23** [quandl/quandl-ruby#23]
hello guys 
i need some help in my first rails application 
when i try to  generate some templates

with the command : 
rails generate scaffold car make:string model:string year:integer

it shows me this message error 
Could not find gem 'sqlite3 (~> 1.3.13)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.

when i run bundler i got this message error 
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (= 4.2.10) was resolved to 4.2.10, which depends on
      bundler (< 2.0, >= 1.3.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (< 2.0, >= 1.3.0)', which is required by gem 'rails
(= 4.2.10)', in any of the sources.

and this is the Gemfile content :+1: 

source 'https://rubygems.org'

 Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.10'
Use sqlite3 as the database for Active Record
gem 'sqlite3' , '~> 1.3.13'
 Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
 Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
 Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
 See https://github.com/rails/execjs#readme for more supported runtimes
 gem 'therubyracer', platforms: :ruby

 Use jquery as the JavaScript library
gem 'jquery-rails'
 Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
 Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
 bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '>= 0.4.0', group: :doc

 Use ActiveModel has_secure_password
 gem 'bcrypt', '~> 3.1.7'
 Use Unicorn as the app server
 gem 'unicorn'

 Use Capistrano for deployment
 gem 'capistrano-rails', group: :development

group :development, :test do
 Call 'byebug' anywhere in the code to stop execution and get a debugger console
 gem 'byebug'
end

group :development do
 Access an IRB console on exception pages or by using <%= console %> in views
 gem 'web-console', '~> 2.0'

 Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

![screenshot at 2019-02-23 19-36-07](https://user-images.githubusercontent.com/46091565/53290225-04751880-37b2-11e9-8190-cf7e33ee7a60.png)
![screenshot at 2019-02-23 19-31-44](https://user-images.githubusercontent.com/46091565/53290226-04751880-37b2-11e9-81bb-20c1a87d325b.png)

**Comment by A-Scott-Rowe** [comment]
Hi @umran23,

Are you also including `quandl-ruby` in the gemfile? 

Either way it looks like you need to install an older version of Bundler or a newer version or Rails.

**Comment by A-Scott-Rowe** [comment]
I am going to close this issue. Feel free to open it back up if you continue to have problems.
