### ISSUE TITLE
Bundler could not find compatible versions for gem "activesupport"

### ISSUE THREAD

**Issue by MahantPatil** [quandl/quandl-ruby#25]
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    cocoapods (~> 1.9.3) was resolved to 1.9.3, which depends on
      activesupport (>= 4.0.2, < 5)

    ion_develop_rails (~> 7.4) was resolved to 7.6.0, which depends on
      activesupport (>= 5.0)

I am getting this error if i do bundle update. Earlier ther cocoapods version was 1.0.1 and i have updated it to 1.9.3

**Comment by A-Scott-Rowe** [comment]
Hi @MahantPatil,

Is the quandl gem also included in your gemfile? We do not have an upper bound on activesupport. Any more info you can provide on how this is related to the quandl gem would be great. 

I'm going to close this issue, but feel free to reopen it with more feedback.
