### ISSUE TITLE
Support for searching

### ISSUE THREAD

**Issue by smostovoy** [quandl/quandl-ruby#7]
Python lib supports searching. 
This is a very handy feature, considering the size of databases.
Any plans?

**Comment by mbasset** [comment]
Hi Smostovoy,

You can use the `all` commands (`Quandl::Database.all()` and `Quandl::Dataset.all()`) in our new package to search for databases and datasets. An example that searches for databases with gold in them could look like: `Quandl::Database.all(params: { query: ‘gold' })`
