### ISSUE TITLE
JSON Version

### ISSUE THREAD

**Issue by waratuman** [quandl/quandl-ruby#8]
I'm trying to use this gem with a Rails 5 project and the JSON versions are conflicting. I was wondering if the JSON gem needed to be tied to 1.7.7 or if you could update the dependency?

This is the problem I run into:

```
uglifier (>= 1.3.0) was resolved to 2.7.2, which depends on
  json (>= 1.8.0)
```

**Comment by mbasset** [comment]
Hi Waratuman,

Our latest version (1.0.3) has a dependency of json ~ 1.8.3. Could you try updating to that version to see if it address' your issue. If not feel free to open a PR with the revised dependency check and we will put that on our roadmap.

**Comment by waratuman** [comment]
You are correct, I have no idea how I got an old version. Thanks!
